repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      -  id: check-byte-order-marker
      -  id: check-case-conflict
      -  id: check-merge-conflict
      -  id: check-symlinks
      -  id: end-of-file-fixer
      -  id: mixed-line-ending
      -  id: trailing-whitespace
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/containerscrew/mtoc
    rev: v0.5.0
    hooks:
      - id: mtoc
        args: [ "-e", ".target/", "-e", "./README.md" ]
  # - repo: local
  #   hooks:
  #     - id: cargo-test
  #       name: "cargo test"
  #       entry: cargo test --locked --no-default-features
  #       language: system
  #       description: "Run cargo test with no default features"
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--all', '--']
      # - id: cargo-check
      # - id: clippy
      #   args: ["--", "-D", "warnings", "-D", "unused-imports"]
#  - repo: local
#    hooks:
#      - id: git-cliff
#        name: "CHANGELOG generator"
#        entry: git cliff --output CHANGELOG.md
#        language: system
#        description: "Generate a CHANGELOG.md file using git-cliff"
#        pass_filenames: false
