from_latest_tag = true
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]
[git_hooks.pre-commit]
script = "./scripts/pre-commit.sh"

# [commit_types]
# feat = { changelog_title = "➕ Additional features" }
# fix = { changelog_title = "🪲 Releases" }

[changelog]
path = "CHANGELOG.md"
authors = [
      { username = "containerscrew", signature = "dcrookie" }
]

[bump_profiles]

[packages]
