services:
  nflux:
    build:
      context: ./
      dockerfile: Dockerfile
    image: docker.io/nflux/nflux:latest
    restart: never
    network_mode: host
    cap_add:
      - CAP_BPF
      - CAP_SYS_ADMIN
      - CAP_PERFMON
    security_opt:
       - label=disable
    container_name: nflux
    environment:
      - NFLUX_CONFIG_FILE_PATH=/nflux.toml
    volumes:
      - ${PWD}/nflux.toml:/nflux.toml:z
