group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
unstable_features = true
empty_item_single_line = true
fn_params_layout = "Vertical"
comment_width = 100
format_code_in_doc_comments = true
#imports_layout = "Vertical"
wrap_comments = true
