services:
  # nflux:
  #   image: localhost/containerscrew/nflux:latest
  #   command: "/usr/local/bin/nflux > /tmp/lastlog 2>&1"
  #   net:
  #     - host
  #   environment:
  #     - NFLUX_CONFIG_FILE=/etc/nflux/nflux.toml
  #   volumes:
  #     - ./nflux.toml:/etc/nflux/nflux.toml

  fluent-bit:
    image: docker.io/fluent/fluent-bit:latest
    container_name: fluent-bit
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - ./fluent-bit/fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml
      - ./geoip/GeoLite2-City.mmdb:/opt/GeoLite2-City.mmdb:ro
      - /var/log/nflux/lastlog:/var/log/nflux/lastlog:ro
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    command:
      ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.yaml"]

networks:
  monitoring:
    external: false
    driver: bridge
