server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: xdp-traffic
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /tmp/nflux.log
          job: xdp-traffic

    pipeline_stages:
      - json:
          expressions:
            direction: direction
            protocol: protocol
            src_ip: src_ip
            dst_ip: dst_ip
            dst_port: dst_port
            total_len: total_len
            tcp_flags: tcp_flags

      - drop:
          expression: ".src_ip == null"

      - geoip:
          db: /usr/share/GeoIP/GeoLite2-City.mmdb
          source: src_ip
          db_type: city

      # - drop:
      #     expression: ".geoip_location_latitude == null or .geoip_location_longitude == null"

      - labels:
          direction:
          protocol:
          src_ip:
          dst_ip:
          geoip_city_name:
          geoip_country_name:
          geoip_location_latitude:
          geoip_location_longitude:

      - metrics:
          traffic_bytes_total:
            type: Counter
            source: total_len
            config:
              action: add
              labels:
                direction:
                protocol:
                src_ip:
                dst_ip:
                dst_port:
                geoip_country_name:
                geoip_city_name:
