server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.containerscrew.com:3100/loki/api/v1/push

scrape_configs:
  - job_name: nflux_file_scrape
    static_configs:
      - targets:
          - localhost
        labels:
          job: nflux
          # sudo nflux traffic-control --log-format json > /tmp/nflux.log 2>&1
          __path__: /tmp/nflux.log
