#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop nflux.service >/dev/null 2>&1 || true
        systemctl disable nflux.service >/dev/null 2>&1 || true
    fi
fi

exit 0