services:
  nflux:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    network_mode: host
    cap_add:
       - ALL
    container_name: nflux
    environment:
      - NFLUX_CONFIG_FILE_PATH=/nflux.toml
    volumes:
      - ${PWD}/nflux.toml:/nflux.toml
