services:
  nflux:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    network_mode: host
    cap_add:
      # Required caps:
      #  - CAP_NET_ADMIN
      #  - CAP_BPF
      #  - CAP_PERFMON
      # Insecure, by the moment give all capabilities
      - ALL
    container_name: nflux
    environment:
      - NFLUX_CONFIG_FILE_PATH=/nflux.toml
    volumes:
      - ${PWD}/nflux.toml:/nflux.toml
