services:
  nflux:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    network_mode: host
    cap_add:
       - ALL
      #  - CAP_BPF
      #  - CAP_SYS_ADMIN
      #  - CAP_PERFMON
    security_opt:
       - label=disable
    container_name: nflux
    environment:
      - NFLUX_CONFIG_FILE_PATH=/nflux.toml
    volumes:
      - ${PWD}/nflux.toml:/nflux.toml:z
