#!/bin/bash
set -e

case "$1" in
  remove)
    # Stop the service when the package is removed
    systemctl stop nflux
    ;;
  purge)
    # Remove config and service files during a full purge
    rm -rf /etc/systemd/system/nflux.service
    rm -rf /etc/nflux/nflux.toml
    rm -rf /var/log/nflux
    systemctl daemon-reload
    ;;
esac

exit 0
