#!/bin/bash
set -e

case "$1" in
  remove)
    # Stop the service when the package is removed
    systemctl stop nflux
    ;;
  purge)
    # Remove config and service files during a full purge
    rm -f /etc/systemd/system/nflux.service
    rm -rf /etc/nflux
    systemctl daemon-reload
    ;;
esac

exit 0
