images:
  - location: https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
    arch: x86_64

  - location: https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-arm64.qcow2
    arch: aarch64

vmType: "vz"

# Enable Rosetta for Linux.
# Hint: try `softwareupdate --install-rosetta` if Lima gets stuck at `Installing rosetta...`
# Register rosetta to /proc/sys/fs/binfmt_misc
rosetta:
  enabled: true
  binfmt: true


networks:
  - vzNAT: true

user:
  name: "ebpf"

mounts:
  - location: "~/Documents/Code/Personal/nflux"
    writable: true

memory: "2GiB"
cpus: 2
disk: "15GiB"

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux -o pipefail
      apt update -y
      apt install -y vim gcc make clang bpftool bpftrace linux-headers-$(uname -r) protobuf-compiler

  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      source $HOME/.cargo/env
      rustup install stable && rustup toolchain install nightly --component rust-src
      rustup default nightly
      cargo install bpf-linker
