service:
  Flush: 5
  Daemon: Off
  Log_Level: info
  Parsers_File: /fluent-bit/etc/parsers.conf
  HTTP_Buffer_Size: 2M
  HTTP_Buffer_Max_Size: 10M

pipeline:
  inputs:
    - name: tail
      tag: nflux
      path: /var/log/nflux/lastlog
      multiline: Off
      parser: json
      read_from_head: true

  filters:
    - name: geoip2
      match: "*"
      database: /opt/GeoLite2-City.mmdb
      lookup_key: src_ip
      record:
        - country src_ip %{country.names.en}
        - isocode src_ip %{country.iso_code}
        - latitude src_ip %{location.latitude}
        - longitude src_ip %{location.longitude}

    - name: lua
      match: "*"
      script: /fluent-bit/scripts/geo.lua
      call: geo_point

  # outputs:
  #   - name: stdout
  #     match: "*"
  #     format: json_lines

  outputs:
    - name: opensearch
      match: "*"
      host: opensearch-node1
      port: 9200
      tls.verify: Off
      time_key: "@es_time"
      http_user: admin
      http_passwd: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      tls: On
      type: "_doc"
      Buffer_Size: False
      suppress_type_name: On
      # pipeline: fb_latlon_to_geopoint
      logstash_format: On
      logstash_prefix: node
      retry_limit: 10
      replace_dots: On
