name: Build 🪛

on:
  pull_request:
  push:
    paths:
      - '**.rs'
      - '.github/workflows/build.yml'
    branches:
      - '**'

env:
    CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build the binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: System dependencies
        run: |
          sudo apt-get -y install linux-headers-$(uname -r)

      - name: Rustup
        run: |
          rustup install stable && rustup toolchain install nightly --component rust-src
          rustup default nightly

      - name: Setup dependencies
        run: |
            cargo install bpf-linker

      - name: Run build
        run: cargo build --release --locked
