name: Build 🪛

on:
  pull_request:
  push:
    paths:
      - '**.rs'
      - '.github/workflows/build.yml'
    branches:
      - '**'
    tags:
      - 'v*.*.*'

env:
    CARGO_TERM_COLOR: always

jobs:
  build:
    name: Builf for ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: linux-arm64
            os: ubuntu-22.04-arm64
            target: aarch64-unknown-linux-gnu

          - release_for: linux-amd64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v4

      - name: System dependencies
        run: |
          sudo apt-get -y install linux-headers-$(uname -r) gcc-aarch64-linux-gnu musl-dev musl-tools pkg-config make

      - name: Rustup
        run: |
          rustup install stable && rustup toolchain install nightly --component rust-src
          rustup default nightly
          # rustup target add aarch64-unknown-linux-gnu --toolchain nightly
          # rustup target add x86_64-unknown-linux-gnu --toolchain nightly

      - name: Setup cargo dependencies
        run: |
            cargo install bpf-linker

      - name: Run build
        run: |
          cargo +nightly build --release --locked
          # cargo +nightly build --release --locked --target aarch64-unknown-linux-gnu
