name: Build 🐛

on:
  pull_request:
  push:
    paths:
      - '**.rs'
      - '.github/workflows/build.yml'
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: linux-arm64
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          - release_for: linux-amd64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v4

      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install linux-headers-$(uname -r) make protobuf-compiler

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "nflux-ebpf-v1"
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Rustup
        run: |
          rustup update
          rustup install stable
          rustup toolchain install nightly --component rust-src

      - name: Setup cargo dependencies
        run: |
          cargo install bpf-linker
          cargo install cargo-deb

      - name: Run build
        run: |
          cargo build --release --package nflux --locked

      - name: Generate deb package
        run: |
          cargo deb

      - name: Test package zip
        run: |
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's|.*/||')
          zip -j nflux-${{ matrix.platform.release_for }}-${{ env.TAG_NAME }}.zip target/release/nflux
