name: Lint 🤖

on:
  pull_request:
  push:
    paths:
      - '**.rs'
      - .github/workflows/lint.yml
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  rusfmt:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4

       - uses: dtolnay/rust-toolchain@v1
         with:
           toolchain: nightly
           components: rustfmt

       - name: Check formatting
         run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy

      - name: Check formatting
        run: cargo +nightly clippy --all-features -- -D warnings
