name: Lint 🤖

on:
  pull_request:
  push:
    paths:
      - '**.rs'
      - '.github/workflows/lint.yml'
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  rusfmt:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4

       - uses: dtolnay/rust-toolchain@v1
         with:
           toolchain: nightly
           components: rustfmt

       - name: Check formatting
         run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: System dependencies
        run: |
          sudo apt-get -y install linux-headers-$(uname -r) make

      - name: Rustup
        run: |
          rustup install stable && rustup toolchain install nightly --component rust-src
          rustup component add clippy --toolchain nightly
          rustup default nightly

      - name: Check formatting
        run: cargo clippy --all-features -- -D warnings
