name: Release 📦

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release for ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: linux-arm64
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          - release_for: linux-amd64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set tag
        id: set_tag
        run: |
          # Extract the tag name from the full reference
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's|.*/||')
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"

      - name: System dependencies
        run: |
          sudo apt-get -y install linux-headers-$(uname -r) make

      - name: Rustup
        run: |
          rustup install stable && rustup toolchain install nightly --component rust-src
          rustup default nightly

      - name: Setup cargo dependencies
        run: |
          cargo install bpf-linker

      - name: Run build
        run: |
          cargo +nightly build --release --locked

      - name: Package zip
        run: |
          zip -j nflux-${{ matrix.platform.release_for }}-${{ env.TAG_NAME }}.zip target/release/nflux

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            CHANGELOG.md
            LICENSE
            *.zip

  changelog:
    name: Generate CHANGELOG
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Install git cliff
        run: |
          rustup default stable
          cargo install git-cliff
          cargo install mtoc

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set tag
        id: set_tag
        run: |
          # Extract the tag name from the full reference
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's|.*/||')
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"

      - name: Update CHANGELOG.md in main branch
        run: |
          git checkout main
          git pull origin main
          git config --global user.name 'containerscrew'
          git config --global user.email 'containerscrew@users.noreply.github.com'
          git cliff -o CHANGELOG.md
          mtoc -e .target/ -e ./README.md
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for release ${{ env.TAG_NAME }}"
          git push origin main
