name: Release 📦

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release for ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: linux-arm64
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          - release_for: linux-amd64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set tag
        id: set_tag
        run: |
          # Extract the tag name from the full reference
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's|.*/||')
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"

      - name: System dependencies
        run: |
          sudo apt-get -y install linux-headers-$(uname -r) make

      - name: Rustup
        run: |
          rustup update
          rustup install stable
          rustup toolchain install nightly --component rust-src

      - name: Setup cargo dependencies
        run: |
          cargo install bpf-linker
          cargo install git-cliff
          cargo install mtoc
          cargo install cargo-deb

      - name: Run build
        run: |
          cargo build --release --locked

      - name: Generate deb package
        run: |
          cargo deb

      - name: Package zip
        run: |
          zip -j nflux-${{ matrix.platform.release_for }}-${{ env.TAG_NAME }}.zip target/release/nflux

      - name: Update CHANGELOG.md in main branch
        run: |
          git cliff -o CHANGELOG.md
          mtoc -f CHANGELOG.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            CHANGELOG.md
            LICENSE
            *.deb
            *.zip
