
name: Release 📦

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release for ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: linux-arm64
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          - release_for: linux-amd64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set tag
        id: set_tag
        run: |
          # Extract the tag name from the full reference
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's|.*/||')
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"

      - name: System dependencies
        run: |
          sudo apt-get -y install linux-headers-$(uname -r) make

      - name: Rustup
        run: |
          rustup install stable && rustup toolchain install nightly --component rust-src
          rustup default nightly

      - name: Setup cargo dependencies
        run: |
            cargo install bpf-linker

      - name: Run build
        run: |
          cargo +nightly build --release --locked


      - name: Package zip
        run: |
          make package PLATFORM=${{ matrix.platform.release_for }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: '[Changelog](https://github.com/containerscrew/nflux/blob/main/CHANGELOG.md)'
          files: |
            CHANGELOG.md
            LICENSE
            *.zip
        env:
          token: ${{ secrets.CI_TOKEN }}
          generate_release_notes: true
          append_body: true
          TAG_NAME:

  publish-crate:
    name: Publish crate to creates.io
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish to creates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: false

  changelog:
    name: Generate CHANGELOG
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Install git cliff
        run: |
          rustup default stable
          cargo install git-cliff

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set tag
        id: set_tag
        run: |
          # Extract the tag name from the full reference
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's|.*/||')
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"

      - name: Update CHANGELOG.md in main branch
        run: |
          git checkout main
          git pull origin main
          git config --global user.name 'containerscrew'
          git config --global user.email 'containerscrew@users.noreply.github.com'
          make generate-changelog
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for release ${{ env.TAG_NAME }}"
          git push origin main
